name: evaluate
on:
  workflow_dispatch:
jobs:
  evaluation:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -f https://download.pytorch.org/whl/torch_stable.html -r requirements.txt
      - name: Evaluate
        run: python ci_evaluate.py
