name: monitor-prod
on:
  schedule:
    - cron: '12 */12 * * *' # At minute 12 past every 12th hour.
  workflow_dispatch:
jobs:
  prod-monitoring:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_monitoring_requirements.txt
      - name: Get monitoring metadata
        run: python ci_monitoring.py